# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='foo_service.proto',
  package='pocketdimension.example.foo',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x66oo_service.proto\x12\x1bpocketdimension.example.foo\";\n\x0eMethod1Request\x12\x12\n\nsome_param\x18\x01 \x01(\t\x12\x15\n\ranother_param\x18\x02 \x01(\x01\"\xa4\x02\n\x0fMethod1Response\x12\x13\n\x0binformation\x18\x01 \x01(\t\x12\x18\n\x10\x66ractional_score\x18\x02 \x01(\x01\x12\x1e\n\x16small_integer_metadata\x18\x03 \x01(\x05\x12#\n\x1bunsigned_small_int_metadata\x18\x04 \x01(\r\x12(\n bigger_unsigned_integer_metadata\x18\x05 \x01(\x04\x12K\n\x0b\x64\x61ta_points\x18\x06 \x03(\x0b\x32\x36.pocketdimension.example.foo.Method1Response.InnerData\x1a&\n\tInnerData\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x32r\n\nFooService\x12\x64\n\x07Method1\x12+.pocketdimension.example.foo.Method1Request\x1a,.pocketdimension.example.foo.Method1Response'
)




_METHOD1REQUEST = _descriptor.Descriptor(
  name='Method1Request',
  full_name='pocketdimension.example.foo.Method1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_param', full_name='pocketdimension.example.foo.Method1Request.some_param', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='another_param', full_name='pocketdimension.example.foo.Method1Request.another_param', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=109,
)


_METHOD1RESPONSE_INNERDATA = _descriptor.Descriptor(
  name='InnerData',
  full_name='pocketdimension.example.foo.Method1Response.InnerData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pocketdimension.example.foo.Method1Response.InnerData.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='pocketdimension.example.foo.Method1Response.InnerData.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=404,
)

_METHOD1RESPONSE = _descriptor.Descriptor(
  name='Method1Response',
  full_name='pocketdimension.example.foo.Method1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='information', full_name='pocketdimension.example.foo.Method1Response.information', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fractional_score', full_name='pocketdimension.example.foo.Method1Response.fractional_score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='small_integer_metadata', full_name='pocketdimension.example.foo.Method1Response.small_integer_metadata', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unsigned_small_int_metadata', full_name='pocketdimension.example.foo.Method1Response.unsigned_small_int_metadata', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bigger_unsigned_integer_metadata', full_name='pocketdimension.example.foo.Method1Response.bigger_unsigned_integer_metadata', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_points', full_name='pocketdimension.example.foo.Method1Response.data_points', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_METHOD1RESPONSE_INNERDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=404,
)

_METHOD1RESPONSE_INNERDATA.containing_type = _METHOD1RESPONSE
_METHOD1RESPONSE.fields_by_name['data_points'].message_type = _METHOD1RESPONSE_INNERDATA
DESCRIPTOR.message_types_by_name['Method1Request'] = _METHOD1REQUEST
DESCRIPTOR.message_types_by_name['Method1Response'] = _METHOD1RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Method1Request = _reflection.GeneratedProtocolMessageType('Method1Request', (_message.Message,), {
  'DESCRIPTOR' : _METHOD1REQUEST,
  '__module__' : 'foo_service_pb2'
  # @@protoc_insertion_point(class_scope:pocketdimension.example.foo.Method1Request)
  })
_sym_db.RegisterMessage(Method1Request)

Method1Response = _reflection.GeneratedProtocolMessageType('Method1Response', (_message.Message,), {

  'InnerData' : _reflection.GeneratedProtocolMessageType('InnerData', (_message.Message,), {
    'DESCRIPTOR' : _METHOD1RESPONSE_INNERDATA,
    '__module__' : 'foo_service_pb2'
    # @@protoc_insertion_point(class_scope:pocketdimension.example.foo.Method1Response.InnerData)
    })
  ,
  'DESCRIPTOR' : _METHOD1RESPONSE,
  '__module__' : 'foo_service_pb2'
  # @@protoc_insertion_point(class_scope:pocketdimension.example.foo.Method1Response)
  })
_sym_db.RegisterMessage(Method1Response)
_sym_db.RegisterMessage(Method1Response.InnerData)



_FOOSERVICE = _descriptor.ServiceDescriptor(
  name='FooService',
  full_name='pocketdimension.example.foo.FooService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=406,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='Method1',
    full_name='pocketdimension.example.foo.FooService.Method1',
    index=0,
    containing_service=None,
    input_type=_METHOD1REQUEST,
    output_type=_METHOD1RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOOSERVICE)

DESCRIPTOR.services_by_name['FooService'] = _FOOSERVICE

# @@protoc_insertion_point(module_scope)
